Feature/completar clase unidade
Gontrojon/DXPP_simulacion pull request #2
Opened 2023-01-17 20:15 UTC by Gontrojon

Se ha codificado el contenido de las clases que se van usar.

2023-01-17 20:18 UTC, arieuger approved these changes

2023-01-18 11:36 UTC, noevilamunoz requested changes
A parte dos dous comentarios que vos deixo no código, tedes que botarlle un vistazo a que estades intentando facer o merge contra `main` cando o que buscamos é facer este merge contra `develop`

2023-01-18 11:36 UTC, noevilamunoz commented on Main.cs
> +        Console.Write("Ola mundo!");
**Suxerencia:** Se isto de momento non nos fai falta non é necesario, para evitar futuros problemas é bo hábito únicamente incluír o necesario para evitar ir deixando pequenas cousas como esta polo camiño que nun futuro podémonos esquecer de cambiar ou eliminar.

2023-01-18 11:36 UTC, noevilamunoz commented on Main.cs
> +    public virtual string Info() {
**Dúbida:** Por que virtual? Non sei como tedes plantexado continuar con isto, dependendo diso sería correcto ou podería sobrar.

2023-01-18 16:58 UTC, Gontrojon commented on Main.cs
> +    public virtual string Info() {
El método "Info" sera el que se use para mostrar la cantidad de vida de la unidad por consola, para que cada clase hija de Unidad pueda sobrescribir este método necesita ser declara "virtual".

2023-01-18 17:00 UTC, Gontrojon commented on Main.cs
> +        Console.Write("Ola mundo!");
Si te refieres al "Ola mundo!", es una salida de consola para asegurar que compila y se muestra correctamente la salida de datos por consola. En futuro esa linea sera la que se use para mostrar la información de vida de las unidades.

2023-01-18 17:04 UTC, Gontrojon commented
> A parte dos dous comentarios que vos deixo no código, tedes que botarlle un vistazo a que estades intentando facer o merge contra `main` cando o que buscamos é facer este merge contra `develop`

Ya he cambiado que el merge sea a "develop" por error al iniciarlo no cambie para que seleccionara esta rama y por defecto deje "main", me fijaré en los próximos para no cometer este error.

2023-01-18 17:11 UTC, noevilamunoz approved these changes

2023-01-18 17:12 UTC, merged