implementación info de todas as clases
Gontrojon/DXPP_simulacion pull request #5
Opened 2023-01-19 21:27 UTC by desvidrealuis

Implementación de info das clases fillas é arranxar o getter e setter da clase abstracta

2023-01-19 21:28 UTC, Gontrojon approved these changes

2023-01-19 21:28 UTC, arieuger approved these changes

2023-01-23 16:53 UTC, noevilamunoz requested changes

2023-01-23 16:53 UTC, noevilamunoz commented on Main.cs
>                  turno = rand.Next(0, 2);
Inicializades esta variable antes do `do while` e despóis aquí repetides o mesmo código dentro dos dous if
Podedes facer o seguinte se queredes manter esta estructura e a variable turno:
`do {
    if (turno == 0)  {
        // Do something;
    } else {
        // Do other thing;
    }
`

2023-01-23 16:53 UTC, noevilamunoz commented on Main.cs
>                  turno = rand.Next(0, 2);
`rand.Next(0,2);` é o mesmo que `rand.Next(2);` sendo este último máis lexible

2023-01-23 16:53 UTC, noevilamunoz commented on Main.cs
> +        // Una vez implementado o bucle de xogo esta li�a mostrara a info das unidades
Neste comentario non sei que cambiáchedes pero o github detecta o "ñ" como un caracter que non coñece

2023-01-23 17:34 UTC, noevilamunoz approved these changes

2023-01-23 17:34 UTC, merged